// <auto-generated />
using System;
using AutoGarageManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoGarageManager.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260529022853_AddAppointmentServices")]
    partial class AddAppointmentServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoGarageManager.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointment_date");

                    b.Property<int?>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("AppointmentId")
                        .HasName("p_k_appointments");

                    b.HasIndex("AppointmentDate")
                        .HasDatabaseName("idx_appointments_appointment_date");

                    b.HasIndex("CarId")
                        .HasDatabaseName("i_x_appointments_car_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_appointments_customer_id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AutoGarageManager.Models.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointment_service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentServiceId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("service_name");

                    b.HasKey("AppointmentServiceId")
                        .HasName("p_k_appointment_services");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("idx_appointment_services_appointment_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_appointment_services_service_id");

                    b.ToTable("appointment_services");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("brand");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("CarId")
                        .HasName("p_k_cars");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_cars_customer_id");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("idx_cars_license_plate");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("p_k_customers");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_customers_email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_customers_phone_number");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("AutoGarageManager.Models.EmailOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("p_k_email_otps");

                    b.ToTable("email_otps");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.HasKey("Id")
                        .HasName("p_k_employees");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("LaborAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("labor_amount");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<decimal>("PartAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("part_amount");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining_amount");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("VatAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("vat_amount");

                    b.Property<decimal>("VatPercent")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("vat_percent");

                    b.HasKey("InvoiceId")
                        .HasName("p_k_invoices");

                    b.HasIndex("RepairOrderId")
                        .IsUnique()
                        .HasDatabaseName("idx_invoices_repair_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoices_status");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("confirmed_by");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("note");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("p_k_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_payments_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_payments_status");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairDetail", b =>
                {
                    b.Property<int>("RepairDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("repair_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairDetailId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.HasKey("RepairDetailId")
                        .HasName("p_k_repair_details");

                    b.HasIndex("RepairOrderId")
                        .HasDatabaseName("i_x_repair_details_repair_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_repair_details_service_id");

                    b.ToTable("repair_details");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.Property<int>("RepairOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairOrderId"));

                    b.Property<string>("AssignedEmployee")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("assigned_employee");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_date");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("diagnosis");

                    b.Property<DateTime?>("EstimatedCompletionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("estimated_completion_date");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("problem_description");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_date");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("repair_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.Property<string>("TechnicalNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("technical_note");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("technician_name");

                    b.Property<string>("VehicleCondition")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("vehicle_condition");

                    b.HasKey("RepairOrderId")
                        .HasName("p_k_repair_orders");

                    b.HasIndex("CarId")
                        .HasDatabaseName("i_x_repair_orders_car_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_repair_orders_status");

                    b.ToTable("repair_orders");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int")
                        .HasColumnName("spare_part_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_repair_parts");

                    b.HasIndex("RepairOrderId")
                        .HasDatabaseName("i_x_repair_parts_repair_order_id");

                    b.HasIndex("SparePartId")
                        .HasDatabaseName("i_x_repair_parts_spare_part_id");

                    b.ToTable("repair_parts");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("p_k_services");

                    b.ToTable("services");
                });

            modelBuilder.Entity("AutoGarageManager.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id")
                        .HasName("p_k_spare_parts");

                    b.ToTable("spare_parts");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("service_name");

                    b.Property<int?>("SparePartId")
                        .HasColumnType("int")
                        .HasColumnName("spare_part_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_warranties");

                    b.HasIndex("CarId")
                        .HasDatabaseName("i_x_warranties_car_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_warranties_customer_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("i_x_warranties_invoice_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_warranties_service_id");

                    b.HasIndex("SparePartId")
                        .HasDatabaseName("i_x_warranties_spare_part_id");

                    b.ToTable("warranties");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Appointment", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .HasConstraintName("f_k_appointments__cars_car_id");

                    b.HasOne("AutoGarageManager.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__customers_customer_id");

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoGarageManager.Models.AppointmentService", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointment_services_appointments_appointment_id");

                    b.HasOne("AutoGarageManager.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_appointment_services__services_service_id");

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Car", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cars__customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Invoice", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany()
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices__repair_orders_repair_order_id");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Payment", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairDetail", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany("RepairDetails")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_details__repair_orders_repair_order_id");

                    b.HasOne("AutoGarageManager.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_details__services_service_id");

                    b.Navigation("RepairOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_orders_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairPart", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany()
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_parts_repair_orders_repair_order_id");

                    b.HasOne("AutoGarageManager.Models.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_parts__spare_parts_spare_part_id");

                    b.Navigation("RepairOrder");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Warranty", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .HasConstraintName("f_k_warranties_cars_car_id");

                    b.HasOne("AutoGarageManager.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("f_k_warranties_customers_customer_id");

                    b.HasOne("AutoGarageManager.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("f_k_warranties_invoices_invoice_id");

                    b.HasOne("AutoGarageManager.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("f_k_warranties_services_service_id");

                    b.HasOne("AutoGarageManager.Models.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .HasConstraintName("f_k_warranties_spare_parts_spare_part_id");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("Service");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.Navigation("RepairDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
