// <auto-generated />
using System;
using AutoGarageManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoGarageManager.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    partial class GarageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoGarageManager.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brand");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("CarId")
                        .HasName("p_k_cars");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("i_x_cars_customer_id");

                    b.HasIndex("LicensePlate")
                        .HasDatabaseName("idx_cars_license_plate");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("p_k_customers");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_customers_email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_customers_phone_number");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("p_k_employees");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId")
                        .HasName("p_k_invoices");

                    b.HasIndex("RepairOrderId")
                        .HasDatabaseName("i_x_invoices_repair_order_id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.HasKey("PaymentId")
                        .HasName("p_k_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("i_x_payments_invoice_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairDetail", b =>
                {
                    b.Property<int>("RepairDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("repair_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairDetailId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.HasKey("RepairDetailId")
                        .HasName("p_k_repair_details");

                    b.HasIndex("RepairOrderId")
                        .HasDatabaseName("i_x_repair_details_repair_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("i_x_repair_details_service_id");

                    b.ToTable("repair_details");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.Property<int>("RepairOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairOrderId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("repair_date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("status");

                    b.HasKey("RepairOrderId")
                        .HasName("p_k_repair_orders");

                    b.HasIndex("CarId")
                        .HasDatabaseName("i_x_repair_orders_car_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_repair_orders_status");

                    b.ToTable("repair_orders");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RepairOrderId")
                        .HasColumnType("int")
                        .HasColumnName("repair_order_id");

                    b.Property<int>("SparePartId")
                        .HasColumnType("int")
                        .HasColumnName("spare_part_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_repair_parts");

                    b.HasIndex("RepairOrderId")
                        .HasDatabaseName("i_x_repair_parts_repair_order_id");

                    b.HasIndex("SparePartId")
                        .HasDatabaseName("i_x_repair_parts_spare_part_id");

                    b.ToTable("repair_parts");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("p_k_services");

                    b.ToTable("services");
                });

            modelBuilder.Entity("AutoGarageManager.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id")
                        .HasName("p_k_spare_parts");

                    b.ToTable("spare_parts");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_warranties");

                    b.ToTable("warranties");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Car", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cars__customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Invoice", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany()
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices__repair_orders_repair_order_id");

                    b.Navigation("RepairOrder");
                });

            modelBuilder.Entity("AutoGarageManager.Models.Payment", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairDetail", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany("RepairDetails")
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_details__repair_orders_repair_order_id");

                    b.HasOne("AutoGarageManager.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_details__services_service_id");

                    b.Navigation("RepairOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.HasOne("AutoGarageManager.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_orders_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairPart", b =>
                {
                    b.HasOne("AutoGarageManager.Models.RepairOrder", "RepairOrder")
                        .WithMany()
                        .HasForeignKey("RepairOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_parts_repair_orders_repair_order_id");

                    b.HasOne("AutoGarageManager.Models.SparePart", "SparePart")
                        .WithMany()
                        .HasForeignKey("SparePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_repair_parts__spare_parts_spare_part_id");

                    b.Navigation("RepairOrder");

                    b.Navigation("SparePart");
                });

            modelBuilder.Entity("AutoGarageManager.Models.RepairOrder", b =>
                {
                    b.Navigation("RepairDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
